name: Test Xeger
on:
  push:
    branches-ignore:
      - main

jobs:
    lint:
        runs-on: ubuntu-latest
        name: Lint Code

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                python-version: 3.13

            - name: Install black
              run: pip install black

            - name: Run black
              run: black --check .
    test:
        runs-on: ubuntu-latest
        name: Run Tests
        needs: lint

        steps:
            - uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                python-version: 3.13

            - name: Install pipenv
              run: >-
                python3 -m
                pip install
                pipenv
                --user

            - name: Install dependencies
              run: pipenv install --dev

            - name: Run tests
              run: pipenv run pytest